### ISSUE TITLE
A Crash

### ISSUE THREAD

**Issue by HeWillBeDark** [tangzx/EmmyLua-Unity#2]
Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at unity.Services.CSharpWorkspace..ctor() in /Users/runner/work/EmmyLua-Unity-LS/EmmyLua-Unity-LS/unity/Services/CSharpWorkspace.cs:line 20
   at Program.<>c.<<Main>$>b__0_3(IServiceCollection services) in /Users/runner/work/EmmyLua-Unity-LS/EmmyLua-Unity-LS/unity/Main.cs:line 53
   at OmniSharp.Extensions.JsonRpc.JsonRpcOptionsRegistryBase`1.WithServices(Action`1 servicesAction)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(LanguageServerOptions options) in /Users/runner/work/EmmyLua-Unity-LS/EmmyLua-Unity-LS/unity/Main.cs:line 43
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction, IServiceProvider outerServiceProvider, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction)
   at Program.<Main>$(String[] args) in /Users/runner/work/EmmyLua-Unity-LS/EmmyLua-Unity-LS/unity/Main.cs:line 15
   at Program.<Main>(String[] args)
[Info  - 12:29:06 AM] Connection to server got closed. Server will restart.
[Error - 12:29:06 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:29:06 AM] EmmyLuaUnity plugin for vscode. client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
  
  
  macOS: Ventura 13.0.1
  VSCode: 1.73.1
  dotnet:7.0.100

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLua-Unity-LS 应该去这里提问
